-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 22:43:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema collage_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema collage_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `collage_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `collage_db` ;

-- -----------------------------------------------------
-- Table `collage_db`.`classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`classroom` (
  `id` INT NOT NULL,
  `section` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NULL DEFAULT '1',
  `year` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `collage_db`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`parent` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `collage_db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`student` (
  `id` INT UNSIGNED NOT NULL DEFAULT '1',
  `stdname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `date_of_join` VARCHAR(45) NULL DEFAULT NULL,
  `parent_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `parent_id`),
  INDEX `parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `collage_db`.`parent` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `collage_db`.`student_classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`student_classroom` (
  `student_id` INT UNSIGNED NOT NULL,
  `classroom_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `classroom_id`),
  INDEX `fk_classroom_id_idx` (`classroom_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `collage_db`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_id`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `collage_db`.`classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
