-- MySQL Script generated by MySQL Workbench
-- Thu Aug 25 20:32:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema collage_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema collage_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `collage_db` DEFAULT CHARACTER SET utf8 ;
USE `collage_db` ;

-- -----------------------------------------------------
-- Table `collage_db`.`classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`classroom` (
  `id` INT NOT NULL,
  `section` VARCHAR(45) NOT NULL,
  `status` BOOLEAN NULL DEFAULT 1,
  `year` VARCHAR(45) NOT NULL,
  `student_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `collage_db`.`student` (`classroom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collage_db`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`parent` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `status` BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collage_db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`student` (
  `id` INT UNSIGNED NOT NULL DEFAULT 1,
  `stdname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `date_of_join` VARCHAR(45) NULL,
  `classroom_id` INT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `classroom_id_idx` (`classroom_id` ASC) VISIBLE,
  INDEX `parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `classroom_id`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `collage_db`.`classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `collage_db`.`parent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `collage_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `collage_db`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `collage_db`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `collage_db`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collage_db`.`view1`;
USE `collage_db`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
